CREATE TABLE `Project` (
    `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Title` VARCHAR(255) NOT NULL,
    `Description` TEXT,
    `Status` INT DEFAULT 0,
    `StartedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `FinishedAt` TIMESTAMP NULL DEFAULT NULL,
    `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);
