CREATE TABLE Project (
	Id Guid UNSIGNED PRIMARY KEY,
	Title VARCHAR(255) NOT NULL,
	Description TEXT,
	Status INT DEFAULT 0,
	StartedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FinishedAt TIMESTAMP CURRENT_TIMESTAMP,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);