CREATE TABLE `Activities` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `UserId` INT NOT NULL DEFAULT 0,
  `ProjectId` INT NOT NULL DEFAULT 0,
  `Status` INT Default 0,
  `Priority` INT Default 0,
  `StartedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `CompletionDate` TIMESTAMP NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  FOREIGN KEY (`UserId`) REFERENCES `Users`(`Id`),
  FOREIGN KEY (`ProjectId`) REFERENCES `Projects`(`Id`)
);
